# Generated by Django 4.1.10 on 2023-07-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IAM", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name=""),
        ),
    ]
