# Generated by Django 4.1.10 on 2023-07-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IAM", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.TextField(),
        ),
    ]
