# Generated by Django 3.2.17 on 2023-07-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_shared',
            name='file',
            field=models.BinaryField(default=None),
        ),
    ]
