# Generated by Django 4.1.10 on 2023-07-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_auto_20230709_0946"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=30)),
                ("file", models.BinaryField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name="comments",
            name="author",
        ),
        migrations.RemoveField(
            model_name="file_shared",
            name="file",
        ),
        migrations.RemoveField(
            model_name="file_shared",
            name="file_name",
        ),
        migrations.AddField(
            model_name="comments",
            name="User",
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="file_shared",
            name="file_id",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="file_shared",
            name="public",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="comments",
            name="file_id",
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="file_shared",
            name="user_id",
            field=models.BigIntegerField(null=True),
        ),
    ]
