# Generated by Django 4.1.10 on 2023-07-13 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_rename_file_details_filedetails_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filedetails",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 13, 19, 9, 4, 719789)
            ),
        ),
        migrations.AddField(
            model_name="filedetails",
            name="owner",
            field=models.IntegerField(default=1),
        ),
    ]
