# Generated by Django 4.1.10 on 2023-07-14 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_filedetails_created_at_filedetails_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="User",
            new_name="user_id",
        ),
        migrations.AlterField(
            model_name="filedetails",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 14, 8, 48, 25, 561769)
            ),
        ),
    ]
