# Generated by Django 4.1.10 on 2023-07-14 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_rename_user_comments_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filedetails",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 14, 13, 38, 36, 382607)
            ),
        ),
    ]
