# Generated by Django 4.1.10 on 2023-07-14 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_alter_filedetails_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="user_id",
        ),
        migrations.AddField(
            model_name="comments",
            name="author",
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="filedetails",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 14, 13, 44, 58, 991812)
            ),
        ),
    ]
