# Generated by Django 4.1.10 on 2023-07-14 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_comments_created_at_alter_filedetails_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="comments",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 14, 14, 57, 2, 105721)
            ),
        ),
        migrations.AlterField(
            model_name="filedetails",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 14, 14, 57, 2, 105447)
            ),
        ),
    ]
