# Generated by Django 4.1.10 on 2023-07-17 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_alter_comments_content_alter_comments_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 17, 6, 15, 56, 415320)
            ),
        ),
        migrations.AlterField(
            model_name="filedetails",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 17, 6, 15, 56, 415021)
            ),
        ),
    ]
