# Generated by Django 4.1.10 on 2023-07-17 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_alter_comments_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 17, 6, 17, 7, 450792)
            ),
        ),
        migrations.AlterField(
            model_name="filedetails",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 17, 6, 17, 7, 450489)
            ),
        ),
    ]
